[project]
name = "object-detection-mania-workspace"
version = "0.1.0"
description = "Monorepo for my object detection fundamentals and competitions"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # Include my custom package so root scripts can import it easily
    "home-made-od",
    "kagglehub>=1.0.1",
    "opencv-contrib-python>=4.13.0.92",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.2",
]

# Ensure that PyTorch is installed with correct CUDA version based on platform
[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.workspace]
members = [
    "home_made_od",
    "packages/pytorch_modular",
]

[tool.uv.sources]
# My local workspace packages
home-made-od = { workspace = true, editable = true }
mypt = { workspace = true, editable = true }

# These sources, in combination with the index above, ensure that uv sync
# installs the correct CUDA version based on the operating system
torch = [
    { index = "pytorch-cu118", marker = "sys_platform == 'win32'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" }
]
torchvision = [
    { index = "pytorch-cu118", marker = "sys_platform == 'win32'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" }
]
torchaudio = [
    { index = "pytorch-cu118", marker = "sys_platform == 'win32'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" }
]
